"""Agent Access Control and Provider-Neutral Router Architecture (#573 Milestone 0).

Exports core contracts, permissions, roles, error taxonomy, and interfaces.
"""

from research_lab.agent_control.audit import AppendOnlyAuditTrail
from research_lab.agent_control.contracts import (
    HASH_PROFILE,
    AgentAuditRecord,
    AgentExecutionHandle,
    AgentPermissionScope,
    AgentProviderDescriptor,
    AgentResult,
    AgentRoute,
    AgentTask,
    AgentUsageSnapshot,
    ProjectBinding,
    TerminalStatus,
    compute_audit_content_hash,
    compute_result_content_hash,
    compute_route_content_hash,
    compute_task_content_hash,
    compute_task_deterministic_id,
    compute_usage_content_hash,
    validate_audit_hash,
    validate_result_hash,
    validate_route_hash,
    validate_task_hash,
)
from research_lab.agent_control.errors import (
    PermissionDeniedError,
    ProjectBindingError,
    ProviderError,
    ProviderErrorCode,
    ProviderUnavailableError,
    QuotaUnavailableError,
    ResultAcceptanceError,
    TamperDetectionError,
    assert_provider_error_does_not_pollute_scientific_decision,
)
from research_lab.agent_control.permissions import (
    ALL_PERMISSIONS,
    HARD_INVARIANT_FORBIDDEN_PERMISSIONS,
    AgentPermission,
    enforce_hard_invariants,
    validate_permission,
    validate_permissions,
)
from research_lab.agent_control.provider import (
    AgentProvider,
    ProviderAvailability,
)
from research_lab.agent_control.roles import (
    ALL_ROLES,
    DEFAULT_ROLE_POLICIES,
    AgentRole,
    AgentRolePolicy,
    validate_role,
)
from research_lab.agent_control.router import (
    POLICY_VERSION,
    authorize,
    enforce_no_nested_delegation,
    select_agent,
    validate_project_binding,
)

__all__ = [
    "ALL_PERMISSIONS",
    "ALL_ROLES",
    "DEFAULT_ROLE_POLICIES",
    "HARD_INVARIANT_FORBIDDEN_PERMISSIONS",
    "HASH_PROFILE",
    "POLICY_VERSION",
    "AgentAuditRecord",
    "AgentExecutionHandle",
    "AgentPermission",
    "AgentPermissionScope",
    "AgentProvider",
    "AgentProviderDescriptor",
    "AgentResult",
    "AgentRole",
    "AgentRolePolicy",
    "AgentRoute",
    "AgentTask",
    "AgentUsageSnapshot",
    "AppendOnlyAuditTrail",
    "PermissionDeniedError",
    "ProjectBinding",
    "ProjectBindingError",
    "ProviderAvailability",
    "ProviderError",
    "ProviderErrorCode",
    "ProviderUnavailableError",
    "QuotaUnavailableError",
    "ResultAcceptanceError",
    "TamperDetectionError",
    "TerminalStatus",
    "assert_provider_error_does_not_pollute_scientific_decision",
    "authorize",
    "compute_audit_content_hash",
    "compute_result_content_hash",
    "compute_route_content_hash",
    "compute_task_content_hash",
    "compute_task_deterministic_id",
    "compute_usage_content_hash",
    "enforce_hard_invariants",
    "enforce_no_nested_delegation",
    "select_agent",
    "validate_audit_hash",
    "validate_permission",
    "validate_permissions",
    "validate_project_binding",
    "validate_result_hash",
    "validate_role",
    "validate_route_hash",
    "validate_task_hash",
]
