"""Agent Access Control and Provider-Neutral Router Architecture (#573 Milestone 1, Milestone 4).

Exports core contracts, permissions, roles, error taxonomy, transport abstractions,
registry, routing policy/context, memory view layer, and execution preparation handoff boundary.
"""

from research_lab.agent_control.audit import AppendOnlyAuditTrail
from research_lab.agent_control.contracts import (
    HASH_PROFILE,
    AgentAuditRecord,
    AgentExecutionHandle,
    AgentPermissionScope,
    AgentProviderDescriptor,
    AgentResult,
    AgentRoute,
    AgentTask,
    AgentUsageSnapshot,
    ProjectBinding,
    TerminalStatus,
    compute_audit_content_hash,
    compute_result_content_hash,
    compute_route_content_hash,
    compute_route_deterministic_id,
    compute_scope_content_hash,
    compute_scope_deterministic_id,
    compute_task_content_hash,
    compute_task_deterministic_id,
    compute_usage_content_hash,
    compute_usage_deterministic_id,
    validate_audit_hash,
    validate_result_hash,
    validate_route_hash,
    validate_scope_hash,
    validate_task_hash,
    validate_usage_hash,
)
from research_lab.agent_control.errors import (
    PermissionDeniedError,
    ProjectBindingError,
    ProviderError,
    ProviderErrorCode,
    ProviderUnavailableError,
    QuotaUnavailableError,
    ResearchMemoryAccessError,
    ResearchMemoryCategoryError,
    ResearchMemoryLimitError,
    ResearchMemoryPermissionError,
    ResearchMemorySourceCorruptionError,
    ResultAcceptanceError,
    TamperDetectionError,
    assert_provider_error_does_not_pollute_scientific_decision,
)
from research_lab.agent_control.handoff import (
    ExecutionPreparation,
    compute_preparation_content_hash,
    compute_preparation_deterministic_id,
    prepare_execution,
    validate_preparation_hash,
)
from research_lab.agent_control.memory_view import (
    ALL_CATEGORIES,
    ALLOWED_DECISION_TYPES,
    CATEGORY_ALLOWED_DECISIONS,
    DEFAULT_ROLE_ALLOWED_CATEGORIES,
    MemoryAccessReasonCode,
    MemoryViewAuditRecord,
    MemoryViewAuditTrail,
    ResearchMemoryCategory,
    ResearchMemoryEntryView,
    ResearchMemoryQuery,
    ResearchMemoryReadAdapter,
    ResearchMemoryView,
    ResearchMemoryViewPolicy,
    build_research_memory_view,
    validate_category,
)
from research_lab.agent_control.permissions import (
    ALL_PERMISSIONS,
    HARD_INVARIANT_FORBIDDEN_PERMISSIONS,
    AgentPermission,
    enforce_hard_invariants,
    validate_permission,
    validate_permissions,
)
from research_lab.agent_control.provider import (
    AgentProvider,
    ProviderAvailability,
)
from research_lab.agent_control.providers import AntigravityLocalMCPProvider
from research_lab.agent_control.registry import ProviderRegistry
from research_lab.agent_control.roles import (
    ALL_ROLES,
    DEFAULT_ROLE_POLICIES,
    AgentRole,
    AgentRolePolicy,
    validate_role,
)
from research_lab.agent_control.router import (
    POLICY_VERSION,
    authorize,
    enforce_no_nested_delegation,
    select_agent,
    validate_project_binding,
)
from research_lab.agent_control.routing_context import RoutingContext
from research_lab.agent_control.routing_policy import (
    RouteReasonCode,
    RoutingPolicy,
)
from research_lab.agent_control.transport import (
    ProviderConnectionDescriptor,
    ProviderTransportKind,
)
from research_lab.agent_control.transports import (
    CRITICAL_MCP_TOOLS,
    LocalMCPTransport,
    MCPToolResolver,
)

__all__ = [
    "ALLOWED_DECISION_TYPES",
    "ALL_CATEGORIES",
    "ALL_PERMISSIONS",
    "ALL_ROLES",
    "CATEGORY_ALLOWED_DECISIONS",
    "CRITICAL_MCP_TOOLS",
    "DEFAULT_ROLE_ALLOWED_CATEGORIES",
    "DEFAULT_ROLE_POLICIES",
    "HARD_INVARIANT_FORBIDDEN_PERMISSIONS",
    "HASH_PROFILE",
    "POLICY_VERSION",
    "AgentAuditRecord",
    "AgentExecutionHandle",
    "AgentPermission",
    "AgentPermissionScope",
    "AgentProvider",
    "AgentProviderDescriptor",
    "AgentResult",
    "AgentRole",
    "AgentRolePolicy",
    "AgentRoute",
    "AgentTask",
    "AgentUsageSnapshot",
    "AntigravityLocalMCPProvider",
    "AppendOnlyAuditTrail",
    "ExecutionPreparation",
    "LocalMCPTransport",
    "MCPToolResolver",
    "MemoryAccessReasonCode",
    "MemoryViewAuditRecord",
    "MemoryViewAuditTrail",
    "PermissionDeniedError",
    "ProjectBinding",
    "ProjectBindingError",
    "ProviderAvailability",
    "ProviderConnectionDescriptor",
    "ProviderError",
    "ProviderErrorCode",
    "ProviderRegistry",
    "ProviderTransportKind",
    "ProviderUnavailableError",
    "QuotaUnavailableError",
    "ResearchMemoryAccessError",
    "ResearchMemoryCategory",
    "ResearchMemoryCategoryError",
    "ResearchMemoryEntryView",
    "ResearchMemoryLimitError",
    "ResearchMemoryPermissionError",
    "ResearchMemoryQuery",
    "ResearchMemoryReadAdapter",
    "ResearchMemorySourceCorruptionError",
    "ResearchMemoryView",
    "ResearchMemoryViewPolicy",
    "ResultAcceptanceError",
    "RouteReasonCode",
    "RoutingContext",
    "RoutingPolicy",
    "TamperDetectionError",
    "TerminalStatus",
    "assert_provider_error_does_not_pollute_scientific_decision",
    "authorize",
    "build_research_memory_view",
    "compute_audit_content_hash",
    "compute_preparation_content_hash",
    "compute_preparation_deterministic_id",
    "compute_result_content_hash",
    "compute_route_content_hash",
    "compute_route_deterministic_id",
    "compute_scope_content_hash",
    "compute_scope_deterministic_id",
    "compute_task_content_hash",
    "compute_task_deterministic_id",
    "compute_usage_content_hash",
    "compute_usage_deterministic_id",
    "enforce_hard_invariants",
    "enforce_no_nested_delegation",
    "prepare_execution",
    "select_agent",
    "validate_audit_hash",
    "validate_category",
    "validate_permission",
    "validate_permissions",
    "validate_preparation_hash",
    "validate_project_binding",
    "validate_result_hash",
    "validate_role",
    "validate_route_hash",
    "validate_scope_hash",
    "validate_task_hash",
    "validate_usage_hash",
]
